FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04

WORKDIR /app

ENV UV_PYTHON=3.12
ENV PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cu122"
ENV PATH="/root/.local/bin:${PATH}"

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY . .

CMD ["uv", "run", "--no-dev", "python", "-m", "src.main"]
